verbose: true

bot:
  name: codesake-bot
  version: 1.0
  email: paolo@codesake.com
  # This overrides any behaviour file passed as argument
  behaviour: codesake-bot.rb
  db:
    enabled:  true
    adapter:  'sqlite3'
    db_name:  'scan_with_dawn.db'

twitter:
  enabled: true
  name: codesake
  consumer_key: "CI6TibDIuuc2VDplfenP7Q"
  consumer_secret: "TH75xzgWJDjznRfIIVJF7OGFXA4PlmARCC8sQ1QvE4"
  oauth_token: "269768424-pvTaj9B6RrDsqfG3QsklsbrIQVei0L6gGUIga4mj"
  oauth_token_secret: "u6fCijvuBFMKoNRbpTqijSFeKO9p5Wu3ybQ7kyxUOCE"

task:
  - { schedule: every 10 m, action: find_scanwithdawn }
  - { schedule: every 15 m, action: find_helobot }
  - { schedule: every 3 h, action: promote_dawn }
  - { schedule: every 1 h, action: mark }
  - { schedule: every 1 d, action: dump_requests }


